<a href="https://colab.research.google.com/github/shawakash/Ml-Projects/blob/Pytorch/00_pytorch_basic_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello, pytorch")

Hello, pytorch


In [ ]:
!nvidia-smi

Mon Jul 24 13:52:56 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
print(torch.__version__)

2.0.1+cu118


In [ ]:
# Scalar Creation
scalar = torch.tensor(1)
scalar

tensor(1)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

1

In [ ]:
scalar = torch.tensor(68)

In [ ]:
scalar

tensor(68)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

68

In [ ]:
vector = torch.tensor([23, 45])
vector

tensor([23, 45])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
vector = torch.tensor([23, 23, 23])

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
matrix.shape

torch.Size([3, 3])

In [ ]:
matrix.ndim

2

In [ ]:
scalar.shape

torch.Size([])

In [ ]:
tensor = torch.tensor([[[1,2,3], [4,5,6], [6,7,8]],[[2,3,2], [2,3,4],[2,3,4]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]],

        [[2, 3, 2],
         [2, 3, 4],
         [2, 3, 4]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([2, 3, 3])

In [ ]:
tensor_rand = torch.rand(size=(3,4))
tensor_rand

tensor([[0.6679, 0.7702, 0.9164, 0.4838],
        [0.9283, 0.1231, 0.4918, 0.0299],
        [0.0731, 0.1180, 0.4655, 0.6380]])

In [ ]:
tensor_rand.dtype

torch.float32

In [ ]:
image_tensor_rand = torch.rand(size=(224, 224, 3))
image_tensor_rand

tensor([[[0.2040, 0.8983, 0.8214],
         [0.7610, 0.9607, 0.1834],
         [0.0696, 0.0403, 0.9218],
         ...,
         [0.4968, 0.9144, 0.8900],
         [0.4277, 0.7545, 0.4780],
         [0.2900, 0.0129, 0.4915]],

        [[0.2358, 0.0547, 0.7492],
         [0.9911, 0.9757, 0.1555],
         [0.5230, 0.7873, 0.0856],
         ...,
         [0.7821, 0.4448, 0.5120],
         [0.5134, 0.4735, 0.4187],
         [0.6220, 0.6159, 0.4428]],

        [[0.1577, 0.9602, 0.7286],
         [0.3709, 0.6082, 0.3561],
         [0.3070, 0.3177, 0.4000],
         ...,
         [0.0915, 0.9888, 0.1263],
         [0.4042, 0.5343, 0.7882],
         [0.3690, 0.4798, 0.3538]],

        ...,

        [[0.1333, 0.3607, 0.8319],
         [0.7243, 0.3997, 0.3803],
         [0.1898, 0.8744, 0.7258],
         ...,
         [0.3745, 0.8895, 0.8134],
         [0.4271, 0.6748, 0.8957],
         [0.9082, 0.4383, 0.1290]],

        [[0.8290, 0.7546, 0.4732],
         [0.2231, 0.5013, 0.2326],
         [0.

In [ ]:
image_tensor_rand.shape

torch.Size([224, 224, 3])

In [ ]:
image_tensor_rand.ndim

3

In [ ]:
zero_tensor = torch.zeros(size=(3,3))
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
zero_tensor.dtype

torch.float32

In [ ]:
ones_tensor = torch.ones(size=(3,3))
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
range_rand_tensor = torch.arange(2, 20, 1)
range_rand_tensor

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
range_rand_tensor.ndim, range_rand_tensor.shape

(1, torch.Size([6]))

In [ ]:
similar_zero_tensor = torch.zeros_like(zero_tensor)
similar_zero_tensor.shape, zero_tensor.shape

(torch.Size([3, 3]), torch.Size([3, 3]))

In [ ]:
similar_ones_tensor = torch.ones_like(ones_tensor)
similar_ones_tensor.shape, ones_tensor.shape

(torch.Size([3, 3]), torch.Size([3, 3]))

In [ ]:
float_32_tensor = torch.tensor([1.0, 2.0, 3.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.dtype


torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
multi = float_16_tensor * float_32_tensor
multi.dtype

torch.float32

In [ ]:
rand_tensor = torch.rand(3,4)
print(rand_tensor)
rand_tensor.shape, rand_tensor.device, rand_tensor.dtype

tensor([[0.9238, 0.1818, 0.7617, 0.4710],
        [0.3170, 0.0949, 0.3164, 0.1416],
        [0.5136, 0.7020, 0.5275, 0.2649]])


(torch.Size([3, 4]), device(type='cpu'), torch.float32)

In [ ]:
# Create a tensor
some_tensor = torch.rand(size=(4,4),
                         dtype=torch.float16,
                         device="cuda")

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.6318, 0.4927, 0.1522, 0.3999],
        [0.5239, 0.6372, 0.1031, 0.4639],
        [0.2101, 0.1610, 0.5693, 0.0640],
        [0.0864, 0.4526, 0.0192, 0.4058]], device='cuda:0',
       dtype=torch.float16)
Shape of tensor: torch.Size([4, 4])
Datatype of tensor: torch.float16
Device tensor is stored on: cuda:0


In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 100

tensor([101, 102, 103])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 2)

tensor([3, 4, 5])

In [ ]:
tensor2 = torch.tensor([4, 5, 6])
torch.dot(tensor, tensor2)

tensor(32)

In [ ]:
matrix1 = torch.tensor([[1,2,3], [4,5,6]])
matrix2 = torch.tensor([[4,5,6],[1,2,3], [2,3,4]])
torch.matmul(matrix1, matrix2)

tensor([[12, 18, 24],
        [33, 48, 63]])

In [ ]:
  matrix1 @ matrix2

tensor([[12, 18, 24],
        [33, 48, 63]])

In [ ]:
%%time
torch.matmul(matrix1, matrix2)

CPU times: user 441 µs, sys: 0 ns, total: 441 µs
Wall time: 339 µs


tensor([[12, 18, 24],
        [33, 48, 63]])

In [ ]:
%%time
matrix1 @ matrix2

CPU times: user 0 ns, sys: 570 µs, total: 570 µs
Wall time: 459 µs


tensor([[12, 18, 24],
        [33, 48, 63]])

In [ ]:
matrix1.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [ ]:
matrix1

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
tensorA = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)
tensorB = torch.tensor([[7, 10], [8, 11], [9, 12]], dtype=torch.float32)
tensorA, tensorB

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]))

In [ ]:
tensorB.T

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [ ]:
torch.matmul(tensorA, tensorB.T)

In [ ]:
torch.mm(tensorA, tensorB.T).type(torch.int32)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]], dtype=torch.int32)

In [ ]:
torch.mm(torch.rand(2, 20), torch.rand(20,2))

tensor([[4.9657, 4.2077],
        [3.7351, 2.8358]])

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
x.min()

tensor(0)

In [ ]:
x.max()

tensor(90)

In [ ]:
torch.mean(x, dtype=torch.float32)

tensor(45.)

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.dtype

torch.dtype

In [ ]:
x.dtype

torch.int64

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
import torch

In [ ]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [ ]:
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [ ]:
tensor = torch.arange(10, 100, 10)

In [ ]:
tensor.dtype, tensor

(torch.int64, tensor([10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [ ]:
tensor.type(torch.float32)

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [ ]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8.shape

torch.Size([9])

In [ ]:
torch.reshape(tensor_int8, (9,))

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [ ]:
tensor_float16.reshape((9,))

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
tensor_float16.shape

torch.Size([9])

In [ ]:
x = torch.arange(1.,8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
x_row_stacked = torch.stack([x,x,x,x], dim=0)
x_row_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [ ]:
x_col_stacked = torch.stack([x,x,x,x], dim=1)
x_col_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [ ]:
print(f"Previous Tensor: {x_reshaped}")
print(f"Previous Shape: {x_reshaped.shape}")
print(f"\nAfter Squeezing\n")

x_squeezed = x_reshaped.squeeze()
print(f"After Squeezing: {x_squeezed}")
print(f"After Squeezing: {x_squeezed.shape}")

Previous Tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous Shape: torch.Size([1, 7])

After Squeezing

After Squeezing: tensor([5., 2., 3., 4., 5., 6., 7.])
After Squeezing: torch.Size([7])


In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [ ]:
x_second_permuted = x_original.permute(0, 2, 1)
x_second_permuted , x_second_permuted.shape

In [ ]:
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0], x[0][2], x[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([7, 8, 9]),
 tensor(1))

In [ ]:
x[0][:, 1]

tensor([2, 5, 8])

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
x[0,2,2]

tensor(9)

In [ ]:
x[0,:,2]

tensor([3, 6, 9])

In [1]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, array.dtype, tensor, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [2]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [3]:
tensor = torch.ones(7)
array_from_tensor = tensor.numpy()
array_from_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1.]))

In [120]:
random_tensor_A = torch.rand(3,2)
random_tensor_B = torch.rand(3,2)
random_tensor_A == random_tensor_B

tensor([[False, False],
        [False, False],
        [False, False]])

In [128]:
import torch
import random

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.random.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

random_tensor_C, random_tensor_D, random_tensor_C == random_tensor_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [5]:
!nvidia-smi


Tue Jul 25 03:16:58 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [19]:
import torch
torch.cuda.is_available()

True

In [20]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [21]:
torch.cuda.device_count()

1

In [22]:
tensor = torch.rand(3,3)
tensor, tensor.device

(tensor([[0.7176, 0.3446, 0.1983],
         [0.1464, 0.1978, 0.4107],
         [0.3392, 0.5907, 0.5158]]),
 device(type='cpu'))

In [23]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([[0.7176, 0.3446, 0.1983],
        [0.1464, 0.1978, 0.4107],
        [0.3392, 0.5907, 0.5158]], device='cuda:0')

tensor([[0.7176, 0.3446, 0.1983],
        [0.1464, 0.1978, 0.4107],
        [0.3392, 0.5907, 0.5158]], device='cuda:0')

In [26]:
tensor_on_cpu = tensor_on_gpu.cpu()
array = tensor_on_cpu.numpy()
array

array([[0.71764034, 0.3446241 , 0.19825041],
       [0.14639366, 0.19781256, 0.41067004],
       [0.33918983, 0.59069467, 0.5158118 ]], dtype=float32)

In [2]:
import torch
import random
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.7513, 0.6387, 0.0367, 0.2979, 0.7530, 0.5603, 0.8907],
        [0.4734, 0.4226, 0.3716, 0.2948, 0.0790, 0.4310, 0.6241],
        [0.0968, 0.4913, 0.2516, 0.2792, 0.5240, 0.8021, 0.7107],
        [0.4136, 0.2807, 0.8608, 0.7958, 0.6731, 0.7311, 0.3937],
        [0.0013, 0.1982, 0.7105, 0.4927, 0.8050, 0.1050, 0.8299],
        [0.3705, 0.7487, 0.5157, 0.3795, 0.0436, 0.6361, 0.3938],
        [0.8449, 0.6074, 0.4022, 0.0536, 0.5216, 0.3848, 0.5900]])

In [37]:
random_tensor_2 = torch.rand(1,7)
torch.mm(random_tensor, random_tensor_2.T)

tensor([[1.1061],
        [0.9868],
        [1.8999],
        [0.7716],
        [1.3174],
        [1.6353],
        [1.7395]])

In [38]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(7,7)
torch.random.manual_seed(RANDOM_SEED)
random_tensor_2 = torch.rand(1,7)
torch.mm(random_tensor, random_tensor_2.T), torch.mm(random_tensor, random_tensor_2.T).shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

In [7]:
torch.cuda.manual_seed(1234)
tensor1 = torch.rand((2,3), device='cuda')
torch.random.manual_seed(1234)
tensor2 = torch.rand((2,3), device='cuda')
tensor1, tensor2

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'))

In [10]:
multi_tensor = torch.mm(tensor1, tensor2.T)
multi_tensor, torch.mm(tensor1, tensor2.T).shape

(tensor([[0.9792, 0.8358],
         [0.8358, 1.4578]], device='cuda:0'),
 torch.Size([2, 2]))

In [11]:
multi_tensor.max(), multi_tensor.min()

(tensor(1.4578, device='cuda:0'), tensor(0.8358, device='cuda:0'))

In [12]:
multi_tensor.argmax(), multi_tensor.argmin()

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))

In [13]:
torch.manual_seed(7)
rand_tensor = torch.rand((1,1,1,10))
rand_tensor_squeezed = rand_tensor.squeeze()
rand_tensor, rand_tensor.shape, rand_tensor_squeezed, rand_tensor_squeezed.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))